services:
  ping-server:
    container_name: ping-server
    image: ping-server
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ../.bin:/app
#      - "/etc/timezone:/etc/timezone:ro"
#      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - ../.env
    command: ["sh", "-c", "/app/ping-server"]